# Generated by Django 4.1.3 on 2023-05-10 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(max_length=30)),
                ('no_of_seats', models.CharField(max_length=10)),
                ('date', models.CharField(max_length=20)),
                ('time1', models.CharField(max_length=20)),
                ('time2', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
                ('course_fee', models.CharField(max_length=30)),
                ('course_duration', models.CharField(default=1, max_length=20)),
                ('class_duration', models.CharField(max_length=20)),
                ('available_seats', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('house_name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('pin', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='institute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager', models.CharField(default=1, max_length=50)),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('pin', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=10)),
                ('image', models.CharField(max_length=200)),
                ('website', models.CharField(default=1, max_length=500)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('rent_amount', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=200)),
                ('imageinstru', models.CharField(default=0, max_length=200)),
                ('CATEGORY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('rent_amount', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=50)),
                ('image', models.CharField(default=0, max_length=200)),
                ('CATEGORY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10)),
                ('amount', models.CharField(max_length=20)),
                ('payment_type', models.CharField(max_length=20)),
                ('CUSTOMER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='return_entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('issue_date', models.CharField(max_length=20)),
                ('return_date', models.CharField(max_length=20)),
                ('amount', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(default=1, max_length=50)),
                ('shop_name', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=30)),
                ('pin', models.CharField(default=1, max_length=6)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=30)),
                ('image', models.CharField(default=1, max_length=500)),
                ('shop_web', models.CharField(default=1, max_length=500)),
                ('status', models.CharField(max_length=10)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('pin', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=10)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('house_name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('pin', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=10)),
                ('BATCH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.batch')),
                ('COURSE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.course')),
                ('INSTITUTE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.institute')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='std_complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10)),
                ('compalint', models.CharField(max_length=100)),
                ('reply', models.CharField(max_length=100)),
                ('STUDENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.student')),
            ],
        ),
        migrations.CreateModel(
            name='shopreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=100)),
                ('date', models.CharField(default=1, max_length=15)),
                ('SHOP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.shop')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='shop_gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.CharField(default=0, max_length=500)),
                ('image2', models.CharField(default=0, max_length=500)),
                ('image3', models.CharField(default=0, max_length=500)),
                ('SHOP', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='myapp.shop')),
            ],
        ),
        migrations.CreateModel(
            name='schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=10)),
                ('COURSE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.course')),
                ('INSTITUTE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.institute')),
            ],
        ),
        migrations.CreateModel(
            name='review_st',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=100)),
                ('STUDENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.student')),
            ],
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=100)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='requst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requ', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('CUSTOMER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.customer')),
                ('INSTRUMENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.instrument')),
                ('MATERIAL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.material')),
            ],
        ),
        migrations.CreateModel(
            name='rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.CharField(max_length=20)),
                ('return_date', models.CharField(max_length=20)),
                ('amount', models.CharField(max_length=20)),
                ('INSTRUMENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.instrument')),
                ('MATERIAL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.material')),
                ('PAYMENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.payment')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='STUDENT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.student'),
        ),
        migrations.CreateModel(
            name='material_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('MATERIAL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.material')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.AddField(
            model_name='material',
            name='SHOP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.shop'),
        ),
        migrations.CreateModel(
            name='instrument_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('INSTRUMENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.instrument')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.AddField(
            model_name='instrument',
            name='SHOP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.shop'),
        ),
        migrations.AddField(
            model_name='institute',
            name='LOGIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login'),
        ),
        migrations.CreateModel(
            name='instireview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default=1, max_length=13)),
                ('review', models.CharField(max_length=100)),
                ('INSTITUTE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.institute')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='insti_gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.CharField(default=0, max_length=500)),
                ('image2', models.CharField(default=0, max_length=500)),
                ('image3', models.CharField(default=0, max_length=500)),
                ('INSTITUTE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.institute')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='LOGIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login'),
        ),
        migrations.CreateModel(
            name='coursebooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.CharField(max_length=20)),
                ('payment_type', models.CharField(max_length=20)),
                ('COURSE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.course')),
                ('PAYMENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.payment')),
                ('STUDENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.student')),
            ],
        ),
        migrations.CreateModel(
            name='course_requst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('INSTITUTE', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.institute')),
                ('USER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='INSTITUTE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.institute'),
        ),
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10)),
                ('compalint', models.CharField(max_length=100)),
                ('reply', models.CharField(max_length=100)),
                ('LOGIN', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.login')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='SHOP',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.shop'),
        ),
        migrations.AddField(
            model_name='batch',
            name='COURSE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.course'),
        ),
        migrations.AddField(
            model_name='batch',
            name='INSTITUTE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.institute'),
        ),
    ]
