# Generated by Django 4.1.3 on 2023-05-17 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_institute_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='COURSE',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='INSTITUTE',
        ),
        migrations.RemoveField(
            model_name='std_complaint',
            name='STUDENT',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='STUDENT',
        ),
        migrations.AddField(
            model_name='instrument_request',
            name='from_date',
            field=models.CharField(default=1, max_length=20),
        ),
        migrations.AddField(
            model_name='instrument_request',
            name='to_date',
            field=models.CharField(default=1, max_length=20),
        ),
        migrations.AddField(
            model_name='instrument_request',
            name='total_amount',
            field=models.CharField(default=1, max_length=50),
        ),
        migrations.AddField(
            model_name='material_request',
            name='from_date',
            field=models.CharField(default=1, max_length=20),
        ),
        migrations.AddField(
            model_name='material_request',
            name='to_date',
            field=models.CharField(default=1, max_length=20),
        ),
        migrations.AddField(
            model_name='material_request',
            name='total_amount',
            field=models.CharField(default=1, max_length=50),
        ),
        migrations.DeleteModel(
            name='coursebooking',
        ),
        migrations.DeleteModel(
            name='schedule',
        ),
        migrations.DeleteModel(
            name='std_complaint',
        ),
    ]
