# Generated by Django 4.1.3 on 2023-05-22 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_schedule_course_remove_schedule_institute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='reason',
            field=models.CharField(default=1, max_length=200),
        ),
        migrations.AddField(
            model_name='shop',
            name='reason',
            field=models.CharField(default=1, max_length=200),
        ),
    ]
