# Generated by Django 4.1.3 on 2023-05-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_institute_reason_shop_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='exp_date',
            field=models.CharField(default=1, max_length=50),
        ),
    ]
