# Generated by Django 4.1.3 on 2023-05-27 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_bank_exp_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='account',
            new_name='cnumber',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='ifsc',
        ),
    ]
