
from django.contrib import admin
from django.urls import path, include

from myapp import views

urlpatterns = [
    path('login/',views.login_fun,name="login"),
    path('login_post/',views.login_post,name="login_post"),
    path('home/',views.home,name="home"),
    path('change_pswrd/',views.change_pswrd,name="change_pswrd"),
    path('admin_pswrd_post/',views.admin_pswrd_post,name="admin_pswrd_post"),
    path('view_new_institutes/',views.view_new_institutes,name="view_new_institutes"),
    path('view_new_institutes_post/',views.view_new_institutes_post,name="view_new_institutes_post"),
    path('approve_institute/<str:id>',views.approve_institute,name="approve_institute"),
    path('view_approved_institutes/',views.view_approved_institutes,name="view_approved_institutes"),
    path('view_approved_institutes_post/',views.view_approved_institutes_post,name="view_approved_institutes_post"),
    path('reject_institute/<str:id>',views.reject_institute,name="reject_institute"),
    path('reject_institute_post/',views.reject_institute_post,name="reject_institute_post"),
    path('view_rejected_institutes/',views.view_rejected_institutes,name="view_rejected_institutes"),
    path('view_rejected_institutes_post/',views.view_rejected_institutes_post,name="view_rejected_institutes_post"),
    path('view_shops/',views.view_shops,name="view_shops"),
    path('view_shop_post/',views.view_shop_post,name="view_shop_post"),
    path('approve_shop/<str:id>',views.approve_shop,name="approve_shop"),
    path('view_approved_shops/',views.view_approved_shops,name="view_approved_shops"),
    path('view_approved_shops_post/',views.view_approved_shops_post,name="view_approved_shops_post"),
    path('reject_shop/<str:id>',views.reject_shop,name="reject_shop"),
    path('reject_shop_post/',views.reject_shop_post,name="reject_shop_post"),
    path('view_rejected_shops',views.view_rejected_shops,name="view_rejected_shops"),
    path('view_rejected_shops_post/',views.view_rejected_shops_post,name="view_rejected_shops_post"),
    path('view_regusers/',views.view_regusers,name="view_regusers"),
    path('name_search/',views.name_search,name="name_search"),
    path('view_reviews/',views.view_reviews,name="view_reviews"),
    path('view_student_review/',views.view_student_review,name="view_reviews"),
    path('institute_signup/',views.institute_signup,name="institute_signup"),
    path('instisignup_post/',views.instisignup_post,name="instisignup_post"),
    path('insti_profile/',views.insti_profile,name="insti_profile"),
    path('edit_profile/',views.edit_profile,name="edit_profile"),
    path('edit_profile_post/',views.edit_profile_post,name="edit_profile_post"),
    path('insti_home/',views.insti_home,name="insti_home"),
    path('insti_add_course/',views.insti_add_course,name="insti_add_course"),
    path('course_post/',views.course_post,name="course_post"),
    path('view_course/',views.view_course,name="view_course"),
    path('course_edit/<str:id>',views.course_edit,name="course_edit"),
    path('course_edit_post/',views.course_edit_post,name="course_edit_post"),
    path('insti_add_batch/', views.insti_add_batch, name="insti_add_batch"),
    path('insti_view_batch/',views.insti_view_batch,name="insti_view_batch"),
    path('batch_edit/<str:id>',views.batch_edit,name="batch_edit"),
    path('batch__edit_post/',views.batch__edit_post,name="batch__edit_post"),
    path('batch_post/', views.batch_post, name="batch_post"),
    path('instituion_new_request/',views.instituion_new_request,name="instituion_new_request"),
    path('accept_requ/<str:id>',views.accept_requ,name="accept_requ"),
    path('insti_accptd_req/', views.insti_accptd_req, name="insti_accptd_req"),
    path('reject_requ/<str:id>',views.reject_requ,name="reject_requ"),
    path('insti_rejctd_req/', views.insti_rejctd_req, name="insti_rejctd_req"),
    path('insti_view_complaint/', views.insti_view_complaint, name="insti_view_complaint"),
    path('insti_sent_reply/<mid>',views.insti_sent_reply,name="insti_sent_reply"),
    path('reply_post/',views.reply_post,name="reply_post"),
    path('inst_gallery/', views.inst_gallery, name="inst_gallery"),
    path('gallery_post/', views.gallery_post, name="gallery_post"),
    path('insti_view_gallery/',views.insti_view_gallery,name="insti_view_gallery"),
    path('insti_view_gallery_more/',views.insti_view_gallery_more,name="insti_view_gallery_more"),
    path('delete_gallery/<id>',views.delete_gallery,name="delete_gallery"),
    path('shop_edit_gallery/<str:id>',views.shop_edit_gallery,name="shop_edit_gallery"),
    path('shop_edit_gallery_post/', views.shop_edit_gallery_post, name="shop_edit_gallery_post"),
    path('insti_review/', views.insti_review, name="insti_review"),
    path('insti_changepswrd/', views.insti_changepswrd, name="insti_changepswrd"),
    path('insti_pswrd_post/', views.insti_pswrd_post, name="insti_pswrd_post"),
    path('shop_login/', views.shop_login, name="shop_login"),
    path('shop_signup/',views.shop_signup,name="shop_signup"),
    path('signup_post/',views.signup_post,name="signup_post"),
    path('profile/', views. profile,name=" profile"),
    path('profile_edit/<mid>',views.profile_edit,name="profile_edit"),
    path('profile_edit_post/',views.profile_edit_post,name="profile_edit_post"),
    path('shop_home/',views.shop_home,name="shop_home"),
    path('instru_cat/', views.instru_cat, name="instru_cat"),
    path('shop_addinstru_post/', views.shop_addinstru_post, name="shop_addinstru_post"),
    path('shop_view_category/', views.shop_view_category, name="shop_view_category"),
    path('edit_category/<str:id>', views.edit_category, name="edit_category"),
    path('edit_category_post/', views.edit_category_post, name="edit_category_post"),
    path('add_instruments/', views.add_instruments, name="add_instruments"),
    path('shop_addinstrument_post/', views.shop_addinstrument_post, name="shop_addinstrument_post"),
    path('shop_viewinstrument/', views.shop_viewinstrument, name="shop_viewinstrument"),
    path('edit_instrument/<str:id>', views.edit_instrument, name="edit_instrument"),
    path('edit_instrument_post/', views.edit_instrument_post, name="edit_instrument_post"),
    path('add_material/', views.add_material, name="add_material"),
    path('shop_materialcat_post/', views.shop_materialcat_post, name="shop_materialcat_post"),
    path('add_materials/', views.add_materials, name="add_materials"),

    path('shop_material_post/', views.shop_material_post, name="shop_material_post"),
    path('edit_mat/<id>',views.edit_mat,name="edit_mat"),
    path('edit_mat_post/',views.edit_mat_post,name="edit_mat_post"),

    path('shop_view_material/', views.shop_view_material, name="shop_view_material"),

    path('shop_viewInstrureust/',views.shop_viewInstrureust,name="shop_viewInstrureust"),
    path('shop_viewconfrmInstrureust/',views.shop_viewconfrmInstrureust,name="shop_viewconfrmInstrureust"),
    path('shop_viewrejctdInstrurqust/',views.shop_viewrejctdInstrurqust,name="shop_viewrejctdInstrurqust"),
    path('shop_viewMatreust/',views.shop_viewMatreust,name="shop_viewMatreust"),
    path('shop_viewconfrmMatreust/',views.shop_viewconfrmMatreust,name="shop_viewconfrmMatreust"),
    path('shop_viewrejctdMatreust/',views.shop_viewrejctdMatreust,name="shop_viewrejctdMatreust"),
    path('add_return_entry/', views.add_return_entry, name="add_return_entry"),
    path('returnentry_post/',views.returnentry_post,name="returnentry_post"),
    # path('view_payment/', views.view_payment, name="view_payment"),
    path('shop_review/', views.shop_review, name="shop_review"),
    path('complaint/', views.complaints, name="complaint"),
    path('shop_complaint_post/', views.shop_complaint_post, name="shop_complaint_post"),
    path('shop_view_reply/',views.shop_view_reply,name="shop_view_reply"),
    path('gallery/',views.gallery,name="gallery"),
    path('shop_gallery_post/',views.shop_gallery_post,name="shop_gallery_post"),
    path('shop_view_gallery/',views.shop_view_gallery,name="shop_view_gallery"),
    path('shop_view_gallery_more/',views.shop_view_gallery_more,name="shop_view_gallery_more"),
    path('shop_delete_gallery/<id>', views.shop_delete_gallery, name="shop_delete_gallery"),
    path('view_instrupayment/',views.view_instrupayment,name="view_instrupayment"),
    path('view_instrupayment_post/',views.view_instrupayment_post,name="view_instrupayment_post"),
    path('view_matpayment/',views.view_matpayment,name="view_matpayment"),
    path('view_matpayment_post',views.view_matpayment_post,name="view_matpayment_post"),


    path('and_user_login/',views.and_user_login,name="and_user_login"),
    path('and_usersignup_post/',views.and_usersignup_post,name="and_usersignup_post"),
    path('and_user_profile/',views.and_user_profile,name="and_user_profile"),
    path('and_edit_profile/',views.and_edit_profile,name="and_edit_profile"),
    # path('user_chnge_pswrd/',views.user_chnge_pswrd,name="user_chnge_pswrd"),
    # path('and_user_changepswrd_post/',views.and_user_changepswrd_post,name="and_user_changepswrd_post"),
    path('and_view_insti/',views.and_view_insti,name="and_view_insti"),
    path('and_view_insti_more/',views.and_view_insti_more,name="and_view_insti_more"),
    path('and_insti_request/',views.and_insti_request,name="and_insti_request"),
    path('and_view_request_status/',views.and_view_request_status,name="and_view_request_statu"),
    path('and_sent_insti_review/',views.and_sent_insti_review,name="and_sent_insti_review"),
    path('and_view_insti_review/',views.and_view_insti_review,name="and_view_insti_review"),
    path('and_view_course/',views.and_view_course,name="and_view_course"),
    path('and_view_batch/',views.and_view_batch,name="and_view_batch"),
    # path('and_sent_req/',views.and_sent_req,name="and_sent_req"),
    # path('user_sentrequst_post/',views.user_sentrequst_post,name="user_sentrequst_post"),
    # path('and_view_schedule/',views.and_view_schedule,name="and_view_schedule"),
    path('and_view_insti_gallery/',views.and_view_insti_gallery,name="and_view_insti_gallery"),
    # path('sent_complaint/', views.sent_complaint, name="sent_complaint"),
    # path('and_user_sentcomplint_post/', views.and_user_sentcomplint_post, name="and_user_sentcomplint_post")
    #
    #
    path('and_view_shop_gallery/', views.and_view_shop_gallery, name="and_view_shop_gallery"),

    path('and_view_shop/', views.and_view_shop, name="and_view_shop"),
    path('and_view_shop_more/', views.and_view_shop_more, name="and_view_shop_more"),
    path('and_sent_shop_review/', views.and_sent_shop_review, name="and_sent_shop_review"),
    path('and_view_shop_review/', views.and_view_shop_review, name="and_view_shop_review"),
    path('and_view_category/', views.and_view_category, name="and_view_category"),
    path('and_view_instrument/', views.and_view_instrument, name="and_view_instrument"),
    path('and_view_material/', views.and_view_material, name="and_view_material"),
    path('and_send_material_request/', views.and_send_material_request, name="and_send_material_request"),
    path('and_send_instrument_request/', views.and_send_instrument_request, name="and_send_instrument_request"),
    path('and_view_material_request_status/', views.and_view_material_request_status, name="and_view_material_request_status"),
    path('and_view_instrument_request_status/', views.and_view_instrument_request_status, name="and_view_instrument_request_status"),

    path('and_payment/',views.and_payment,name="and_payment"),
    path('and_send_apprating/',views.and_send_apprating,name="and_send_apprating"),
    path('and_view_apprating/',views.and_view_apprating,name="and_view_apprating"),
    # path('instrument/', views.instrument, name="instrumentt"),
    # path('instrument/', views.instrument, name="instrumentt"),
    # path('sent_requst/', views.sent_requst, name="sent_requst"),
    # path('user_instrurequest_post/', views.user_instrurequest_post, name="user_instrurequest_post"),
    # path('and_user_payment_post/', views.and_user_payment_post, name="and_user_payment_post"),
    # path('and_view_payment/', views.and_view_payment, name="and_view_payment"),
    # path('view_mat/', views.view_mat, name="view_mat"),
    # path('and_view_material/', views.and_view_material, name="and_view_material"),
    # path('sent_matreq/', views.sent_matreq, name="sent_matreq"),
    # path('user_sentrqst_post/', views.user_sentrqst_post, name="user_sentrqst_post"),
    # path('view_shop_gallery/', views.view_shop_gallery, name="view_shop_gallery"),
    # path('view_review/', views.view_review, name="view_review"),
    # path('user_review_post/',views.user_review_post,name="user_review_post"),
    # path('and_view_payment/',views.and_view_payment,name="and_view_payment"),











]
